services:
  pubsub-emulator:
    build:
      context: ../../
      dockerfile: Dockerfile
      cache_from:
        - type=gha,scope=gced
    command:
      - --emulator=pubsub
      - --port=8085
    ports:
      - 8085:8085/tcp
    volumes:
      - ./init.d/:/docker-entrypoint-init.d/ready.d/
