name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Dokerfile lint
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck
        run: shellcheck entrypoint.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: google-cloud-emulator-docker:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-create-pubsub-topic:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: examples/create_pubsub_topic
    steps:
      - uses: actions/checkout@v4
      - name: start emulator
        run: docker compose up -d --wait
      - name: test
        run: |
          curl -s http://localhost:8085/v1/projects/test-project/topics | \
            jq -e '. == {
              "topics": [
                {
                  "name": "projects/test-project/topics/email-notifications"
                },
                {
                  "name": "projects/test-project/topics/push-notifications"
                }
              ]
            }'
