services:
  datastore-emulator:
    build:
      context: ../../
      dockerfile: Dockerfile
      cache_from:
        - type=gha,scope=gced
    command:
      - --emulator=datastore
      - --port=8081
      - --project=test-project
    ports:
      - 8081:8081/tcp
    volumes:
      - ./init.d/:/docker-entrypoint-init.d/ready.d/
